# Generated by Django 2.0.4 on 2018-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='lat',
            new_name='LAT',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='lon',
            new_name='LONG',
        ),
        migrations.AddField(
            model_name='airport',
            name='ALT',
            field=models.FloatField(default=683),
            preserve_default=False,
        ),
    ]
