import json
import pandas as pd

######### INITIALIZE DATAFRAMES #####
SWDF_jan = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_feb = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_mar = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_apr = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_may = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_jun = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_jul = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_aug = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_sep = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_oct = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_nov = pd.DataFrame(columns=['alt','dir','speed'])
SWDF_dec = pd.DataFrame(columns=['alt','dir','speed'])
##############


json_jan_file = open("winds.cha.jan.json")
json_jan_str = json_jan_file.read()
json_jan_data = json.loads(json_jan_str)
SWDF_jan = SWDF_jan.from_dict(json_jan_data)
json_feb_file = open("winds.cha.feb.json")
json_feb_str = json_feb_file.read()
json_feb_data = json.loads(json_feb_str)
SWDF_feb = SWDF_feb.from_dict(json_feb_data)
json_mar_file = open("winds.cha.mar.json")
json_mar_str = json_mar_file.read()
json_mar_data = json.loads(json_mar_str)
SWDF_mar = SWDF_mar.from_dict(json_mar_data)
json_apr_file = open("winds.cha.apr.json")
json_apr_str = json_apr_file.read()
json_apr_data = json.loads(json_apr_str)
SWDF_apr = SWDF_apr.from_dict(json_apr_data)
json_may_file = open("winds.cha.may.json")
json_may_str = json_may_file.read()
json_may_data = json.loads(json_may_str)
SWDF_may = SWDF_may.from_dict(json_may_data)
json_jun_file = open("winds.cha.jun.json")
json_jun_str = json_jun_file.read()
json_jun_data = json.loads(json_jun_str)
SWDF_jun = SWDF_jun.from_dict(json_jun_data)
json_jul_file = open("winds.cha.jul.json")
json_jul_str = json_jul_file.read()
json_jul_data = json.loads(json_jul_str)
SWDF_jul = SWDF_jul.from_dict(json_jul_data)
json_aug_file = open("winds.cha.aug.json")
json_aug_str = json_aug_file.read()
json_aug_data = json.loads(json_aug_str)
SWDF_aug = SWDF_aug.from_dict(json_aug_data)
json_sep_file = open("winds.cha.sep.json")
json_sep_str = json_sep_file.read()
json_sep_data = json.loads(json_sep_str)
SWDF_sep = SWDF_sep.from_dict(json_sep_data)
json_oct_file = open("winds.cha.oct.json")
json_oct_str = json_oct_file.read()
json_oct_data = json.loads(json_oct_str)
SWDF_oct = SWDF_oct.from_dict(json_oct_data)
json_nov_file = open("winds.cha.nov.json")
json_nov_str = json_nov_file.read()
json_nov_data = json.loads(json_nov_str)
SWDF_nov = SWDF_nov.from_dict(json_nov_data)
json_dec_file = open("winds.cha.dec.json")
json_dec_str = json_dec_file.read()
json_dec_data = json.loads(json_dec_str)
SWDF_dec = SWDF_dec.from_dict(json_dec_data)
