# Generated by Django 2.0.4 on 2018-04-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='cruising_altitude',
            field=models.IntegerField(default=3500),
        ),
    ]
