# Generated by Django 2.0.4 on 2018-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_cruising_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='classification',
            field=models.CharField(default='VLJ', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='climb_dist',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='climb_fuel',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='climb_time',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='cruising_fuel_burn_gph',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='cruising_fuel_reserve',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='empty_weight',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='empty_weight_cg',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='make',
            field=models.CharField(default='Eclipse', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_fuel_capacity',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_landing_weight',
            field=models.IntegerField(default=5600),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_takeoff_weight',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='maximum_zero_fuel_weight',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='model',
            field=models.CharField(default='500', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='ramp_max_weight',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='serial',
            field=models.CharField(default='78', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='taxi_fuel',
            field=models.IntegerField(default=4.5),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='type',
            field=models.CharField(default='EA50', max_length=40),
            preserve_default=False,
        ),
    ]
